"""Check changes

Revision ID: c8baaef0514d
Revises: 14bae6772a70
Create Date: 2021-09-27 00:01:45.386080

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8baaef0514d'
down_revision = '14bae6772a70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
